project_name: pbd-cli

builds:
  # Dev version only
  - id: pbd-cli-dev
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}-dev
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -X github.com/PaleBlueDot-AI-Open/pbd-cli/internal/config.env=dev
    main: .

archives:
  - id: pbd-cli-dev
    builds:
      - pbd-cli-dev
    format: tar.gz
    name_template: "{{ .ProjectName }}-dev_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
